-- Generated by `pnpm --filter @kaneo/api db:generate:fork` — do not edit.
-- The complete set of schema changes this fork adds on top of upstream, as a
-- single converging migration. Rerun the script after merging upstream.
-- Statements are idempotent because this file is rewritten and replayed.

ALTER TABLE "project" ADD COLUMN IF NOT EXISTS "auto_archive_done_after_days" integer;--> statement-breakpoint
ALTER TABLE "task" ADD COLUMN IF NOT EXISTS "completed_at" timestamp;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "task_completedAt_idx" ON "task" USING btree ("completed_at");
